### ISSUE TITLE
Data download size descrepancy

### ISSUE THREAD

**Issue by sammlapp** [DBD-research-group/BirdSet#267]
I'm downloading XCL using the following:

```
from birdset.datamodule import DatasetConfig
from birdset.datamodule.birdset_datamodule import BirdSetDataModule

# download a complete xeno canto snapshot included in BirdSet
# https://huggingface.co/datasets/DBD-research-group/BirdSet

# initiate the data module
dm = BirdSetDataModule(
    dataset=DatasetConfig(
        data_dir=".../data_birdset/",
        hf_path="DBD-research-group/BirdSet",
        hf_name="XCL",
        n_workers=4,
        val_split=0.2,
        task="multilabel",
        classlimit=500,
        eventlimit=5,
        sampling_rate=32000,
    ),
)
# prepare the data (download dataset, ...)
dm.prepare_data()
```

Based on the description on HuggingFace I expected  528,434 files, 484 Gb. However, I eventually ran out of storage with the downloaded content hitting over 700 Gb.

Additionally, when I re-started the download, it did not resume downloading but instead started re-downloading into subdirectories with different long random-hexidecimal-character names. 

Two questions: (1) what is the full size of the XCL download; and (2) is there a way to avoid duplicate downloads of the same files using this api? This applies not only to if a download gets interrupted, but also to the case of downloading multiple datasets like XCL and PER: ideally they would reference the same set of files on disk rather than have to store an additional copy of the xeno canto files. 

Edit: I was able to download the entire XCL after clearing up space. The data_birdset/downloads folder is 986G and data_birdset/downloads/extracted is 502G. Should I now delete the files in `downloads` folder? (are they temporary files that were extracted into `downloads/extracted`?) I'm also unclear on how to use the XCL/XCM datasets in general, is there a script somewhere that demonstrates training on XCL? After the download completes and the train/valid split are created using the code above, I get `KeyError: 'test_5s'` which I guess is because this dataset (unlike HSN etc) doesn't contain test data. 

```
Traceback (most recent call last):
  File "/home/sml161/birdset_download/download_XCL.py", line 22, in <module>
    dm.prepare_data()
  File "/home/sml161/BirdSet/birdset/datamodule/base_datamodule.py", line 120, in prepare_data
    dataset = self._preprocess_data(dataset)
  File "/home/sml161/BirdSet/birdset/datamodule/birdset_datamodule.py", line 130, in _preprocess_data
    dataset = DatasetDict({split: dataset[split] for split in ["train", "test_5s"]})
  File "/home/sml161/BirdSet/birdset/datamodule/birdset_datamodule.py", line 130, in <dictcomp>
    dataset = DatasetDict({split: dataset[split] for split in ["train", "test_5s"]})
  File "/home/sml161/miniconda3/envs/birdset/lib/python3.10/site-packages/datasets/dataset_dict.py", line 75, in __getitem__
    return super().__getitem__(k)
KeyError: 'test_5s'
```

**Comment by lurauch** [comment]
Hey :) 

Thanks for catching that! You’re right—the file size displayed on Hugging Face (HF) only reflects the zipped files and not the extracted ones. We’ll look into updating that to avoid any confusion.

**Download process:**
HF should recognize if a download has already started and automatically continue it. If the download is restarting, it might be due to a change in the download folder path?

**Dataset size**:
After unpacking, the dataset should be around **993 GB** total, with the extracted folder taking up about **510 GB**.  TBH we haven’t thought about deleting files outside `/downloads/extracted`, but a quick check suggests that all paths point to the extracted files. This is a great point! Maybe we can add an automatic cleanup step in the builder script to remove unnecessary files—I’ll explore this further.

**HF dataset structure & downloads:**
Here are a few notes on how HF handles data structure and downloads:

- When you download the dataset, HF automatically saves/unpacks it into subdirectories based on HF’s naming conventions.
- Our data natively includes `Audio(decode=False)`, which means preprocessing (using `map` in HF) without decoding will only update the metadata. Using our example code with `save_to_disk`, you’ll need the `/downloads/extracted` folder path to load it properly with `ds = load_from_disk(dm.disk_save_path)`. Our `XCL_processed` folders end up around 6GB, so those downloads need to stay in place.
- If you choose to `save_to_disk` after decoding, HF saves it in Arrow format. This unpacked data might be larger than the original files. In this case, you could delete the entire `/download` folder, though you’d lose the ability to unpack any additional files from the original set.

**Duplicate downloads:**
Duplicate downloads can be an issue, and while we’ve attempted to address this in our HF builder script, afaik HF doesn’t allow a better solution right now. To help minimize duplicates, you could:

1. **Selective downloads**: You can download only specific datasets like `HSN_scape` without pulling XC files again.
2. **Subset creation**: If you need the train subsets, a workaround is to first load XCL, then apply a custom mapping function to filter the specific eBird codes for each test set (we created our subsets this way) and saved them with `save_to_disk`. We’ll look into integrating a simpler subset creation method in BirdSet—thanks for the suggestion!

**Error in XCM/XCL test dataset**:
The error is due to needing a different datamodule for XCM/XCL, as these sets don’t include a specific test dataset. This is covered in the **“ Reproduce Baselines”** section in the docs (that I accidentally removed). Also, you can refer to the configs:

- **Datamodule config**: [XCL.yaml](https://github.com/DBD-research-group/BirdSet/blob/main/configs/datamodule/XCL.yaml)
- **Experiment configs**: [BirdSet NeurIPS24](https://github.com/DBD-research-group/BirdSet/tree/main/configs/experiment/birdset_neurips24/XCL)

If you still need clarification, feel free to reach out here or by email!

**Comment by lurauch** [comment]
@Moritz-Wirth 

Possible solutions list: 

- [ ] **Avoid extracting the files entirely.**  
  This approach works easily if we utilize the `Audio` class from Hugging Face. However, it has two significant drawbacks:  
  - The true file paths would not be accessible.  
  - The `soundfile` library would need to support partial loading of zipped files to load specific events without processing the entire file each time.

- [ ] **Delete the zipped files after extracting them via Hugging Face.**  
  This is the simplest solution but requires additional temporary disk space during extraction. The space is freed afterward, but the temporary demand is still large. 

- [ ] **Delete zipped files during the extraction process via Hugging Face.**  
  Implementing this directly in the dataset builder script may not be possible? and could involve additional complexity.

- [ ] **Re-upload files without zipping them.**  
  Completely omit zipped files by re-uploading all content directly in a usable format, such as `.ogg` or `.flac`.

**Comment by raphaelschwinger** [comment]
@lurauch @Moritz-Wirth 

I would opt for reuploading as `.flac`.

**Comment by Moritz-Wirth** [comment]
Following up for possible solutions:

1. Avoid extracting the files entierly. 
This approach involves making minor modifications to the Hugging Face (HF) dataset builder script and the BirdSet event decoding process. Instead of extracting the audio files, the bytes can be loaded directly from the archive and saved into the HF Arrow files during the dataset build process. Once a portion of the archive is processed, it can be deleted, thereby reducing storage needs.
Loading the bytes is only performed once at the start and is efficient. The resulting Arrow files have the same data size as the extracted audio files. Audio files can still be partially loaded from the bytes using the 'io' and 'soundfile' libraries as before.
   - Pro: 
     - Download as archive
     - Half of storage space needed (at all times)
   - Con:
     - 'filepath' is irrelevant, thus could be removed
     - No direkt access to audio files (only the bytes)

2. Delete the zipped files after extracting them via Hugging Face.
Archives can be deleted once the HF dataset builder finishes processing. This requires minimal modification to the builder script. However, during the download and extraction process, double the required storage space is still needed temporarily.
   - Pro:
     - Simple and no changes except one line in the builder script
     - Direkt access to audio files
   - Con:
     - Temporarly need double the amount of actual storage

3. Delete zipped files during the extraction process via Hugging Face.
Currently, this is not feasible with the existing builder script because the archives are iterated over after extraction. Implementing this approach would require significant modifications to the builder script, as HF does not support this natively.
**If** implementation is possible, audio files would be directly accessible, and double storage usage could be avoided entirely.

4. Re-upload files without zipping them.
This would include re-uploading the audio files in an unzipped format, updating the metadata file paths, and modifying the builder script accordingly. While it avoids double storage space requirements, downloading individual audio files might increase the total download time.
   - Pro:
     - Half of storage space needed (at all times)
     - Direkt access to audio files
   - Con:
     - Re-upload of all audio files and changes in metadata files
     - Audio files are downloaded individually
     - larger builder script changes/rewrite


## Regarding different audio formats
@raphaelschwinger 
I've tested common different audio formats using a subset of 687 audio files.
The original files are in ogg format and are reformated.
Unsigned 8 bit PCM (PCM8) is possible, tho not tested at the moment.

File size:
ogg: 25MB
flac (PCM16): 88MB
flac (PCM24): 210MB
wav (PCM16): 243MB
wav (PCM24): 365MB
npy: 975MB

Loading speed (avarage of 7 runs, without caching): 
ogg: 3.79 s
flac (16 PCM): 4.44 s
flac (24 PCM): 5.61 s
wav (16 PCM): 1.18 s
wav (24 PCM): 1.98 s
npy: 320 ms

**Comment by sammlapp** [comment]
I would put a strong vote in for ending up with audio files rather than some encoded format. This greatly expands the usability of the downloaded content for any downstream use case without requiring the use of specific BirdSet classes. Even something as simple as opening and playing back the audio file would become complicated if audio files are not available.

**Comment by lurauch** [comment]
> I would put a strong vote in for ending up with audio files rather than some encoded format. This greatly expands the usability of the downloaded content for any downstream use case without requiring the use of specific BirdSet classes. Even something as simple as opening and playing back the audio file would become complicated if audio files are not available.


Thanks for your take on this @sammlapp! 

Unfortunately, that’s my biggest concern as well. This was the issue I had with the current AudioSet implementation available on HF. @Moritz-Wirth, it might be worth sending an email to Quentin from HF after all. They might have a solution for this - it cannot be an uncommon problem.

**Comment by Moritz-Wirth** [comment]
We implemented:
> 3. Delete zipped files during the extraction process via Hugging Face.

This combines the best of both worlds.
- Only need half stoage space at all times.
- Direct access to audio files, in the Hugging Face cache folder
